Prospress/woocommerce-subscriptions-gifting

- templates/html-add-recipient.php
Pass _"This is a gift"_ label through a filter so that it can be customised without the need for overriding the template. Also make sure _Recipient's Email Address:_ is made available for translation.
> Add filter to "This is a gift" text and improve i18n of recipient template

- includes/class-wcsg-cart.php
When adding a product to the cart from the shop/product archive page, the mini cart will be incorrectly generated with interactive gifting fields.
Before: https://cloudup.com/iP05CfAz2Sz
After adding the daily product from the shop page: https://cloudup.com/inasA0BMAKY
This PR uses a more consistent and reliable approach to determining if the `woocommerce_cart_item_name` is being generated for the mini cart or cart page rather than the approach introduced in https://github.com/Prospress/woocommerce-subscriptions-gifting/commit/a0e2b2238d9a03d8660efe6d91c688aaf0439dcf.
> Fix interactive gifting fields being added to the mini cart in some situations

- includes/class-wcsg-cart.php
see #132 for issue description
**Steps to replicate in `master`:**
Initial payment cart:
- Purchase a subscription product and enter a gift recipient
- proceed to PayPal (do not complete payment and return to store)
- go to the My Account page and click *"Pay"* for the new pending order
- notice the recipient email you previously entered is missing.
Resubscribe cart:
- Purchase a subscription product and enter a gift recipient
- complete the checkout
- go to the admin edit subscritpion screen and cancel the subscription
- go back to the My account view subscription page and click **"Resubscribe"**
- notice the recipient email feild is empty.
This PR adds the recipeint meta to the cart item data when setting up the cart with resubscribes and initial payments. 
fixes #132
> Automatically add recipient to resubscribe and initial payment cart items.

- README.md
- includes/class-wcsg-admin.php
- includes/class-wcsg-cart.php
- includes/class-wcsg-checkout.php
- includes/class-wcsg-download-handler.php
- includes/class-wcsg-product.php
- includes/class-wcsg-recipient-addresses.php
- templates/html-add-recipient.php
- woocommerce-subscriptions-gifting.php
This PR includes various changes for supporting stores using Gifting for corporate purchasing.
- Adds a setting allowing store owners to edit the "This is a gift" text displayed on the single product, cart and checkout pages (https://cloudup.com/cM9F2sNRGGe)
- Rephrase user-facing strings which reference the word 'gift', using a more generic term like recipient: 
- The error notice displayed when the customer tries to add products to a gifted subscription renewal cart. (https://cloudup.com/cyAkGtIUirW) 
- The notice explaining that we've loaded the recipient's shipping address into the checkout when manually paying for a gifted subscription renewal order. (https://cloudup.com/cJJJdi7qJzk)
- notes displayed when a customer updates their: 
- billing address (https://cloudup.com/c6RAp9NkK-P) …
> Remove references to 'Gift' in customer facing notices and add "This is a gift" setting 

- includes/class-wcsg-admin.php
Fixes PHP error notice when triggering a PayPal RT subscription renewal order from action scheduler screen.
To replicate: 
1. Add a subscription product with a recipient to cart.
2. Choose PayPal as the payment method on checkout (must have RT enabled)
3. Go to the admin action scheduler screen (**Tools->Scheduled Actions** from the admin dashboard)
4. Find and run the subscription scheduled payment action. 
At this point you should receive the error:
```
PHP Notice:  Trying to get property of non-object in .../wp-content/plugins/woocommerce-subscriptions-gifting/includes/class-wcsg-admin.php on line 70
```
The line in Subscriptions which triggers this issue is [paypal-reference-transaction-api-request L499](https://github.com/Prospress/woocommerce-subscriptions/blob/563ac8d20d32a1cd9892be …
> Check the screen ID property exists before trying to access it

- includes/class-wcsg-cart.php
- includes/class-wcsg-memberships-integration.php
- includes/class-wcsg-product.php
see #155 for background.
This PR replaces all uses of `WC_Subscriptions_Product::is_subscription()` with a filterable function, allowing 3rd parties to enable/disable gifting for a specific product.
fixes #155
> Introduce filterable is giftable product function

- README.md
- woocommerce-subscriptions-gifting.php
Tiny edit to the Plugin file header and README file to add a GPLv2 license.
Uses [shields.io](http://shields.io/). Lots of services include Travis etc. that use the [same standard](https://github.com/badges/shields#services-using-the-shields-standard)
Similar reasoning to https://github.com/Prospress/woocommerce-subscriptions-importer-exporter/pull/135
> Add license info

- includes/class-wcsg-query.php
- woocommerce-subscriptions-gifting.php
Revert the change introduced in https://github.com/Prospress/woocommerce-subscriptions-gifting/pull/105 inline with the revert of the same change in Subscriptions (https://github.com/Prospress/woocommerce-subscriptions/pull/1286).
This PR also introduces the exact same function of the same name from https://github.com/Prospress/woocommerce-subscriptions/pull/1286/commits/2753b93fb90e174f00bc4b0749b5077991e8a375. If there are any ideas on how Gifting could use the same functionality of `WCS_Query::pre_get_posts` without the need to duplicate the function let me know 😄. 
Also did some tidying up so the scripts loaded for the new recipient account details page aren't loaded on every page. 😆
> Revert fix to query vars

- includes/class-wcsg-admin.php
Introduces `WCSG_Admin::request_query` which adds the meta query to also check for the customer ID in `_recipient_user` meta, this will mean subscriptions the customer is the recipient of are also returned when filtering by customer.
**For example:**
- User's subscriptions: https://cloudup.com/ckC4y24jvZd
- Filtering by this customer: 
- `master` https://cloudup.com/cSnCjffn-5e
- `issue_147` https://cloudup.com/cvl9Em6l3DR
fixes #147
> Admin filter subscriptions by recipient

- js/wcs-gifting.js
When submitting the cart form where the active element is a recipient email field, ensure the clicked submit button is the `update_cart` rather than the default `apply_coupon`.
To replicate on `master` 
1. add a subscription product to the cart
2. go to the cart page
3. enter a recipient email address and press enter
You should receive the ['Please enter a coupon code'](https://cloudup.com/cXm8GOseaxl) message
fixes #150
> fix cart form submit by enter press after entering recipient email [WC 2.6]

- includes/class-wcsg-memberships-integration.php
Some Background: When WC Memberships links memberships to subscriptions they link it to the subscription in the order with the product. This criteria isn't specific enough in the case of gifted subscription memberships however so Gifting needs to find the subscription in the order with the product for the recipient - this is the job of [`WCSG_Memberships_Integration::update_subscription_id()`](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/8a8832f7320afbd623dc2ef4bdcac22ab3d7b129/includes/class-wcsg-memberships-integration.php#L143).
However it assumes that if the member user is not equal to the order user that the membership must have been gifted. This might not always be the case and so this PR (200198a):
- makes sure we only attempt to re-link subscriptions with …
> Update and fix Memberships integration

- includes/class-wcsg-cart.php
- includes/class-wcsg-checkout.php
In https://github.com/woothemes/woocommerce/commit/da2337b05ba9c3b80e0ca8dd32ed80d9801dd107, WC changed where the `woocommerce_ship_to_different_address_checked` filter is called from. Because Gifting would return `true` and print a notice when it automatically ships to the renewal recipient, that change would cause the HTML output to be broken.
To replicate on `master`:
- Purchase a subscription product and enter a recipient email
- Trigger a pending payment or failed renewal order
- Go to the My Account page and Click "Pay"
- Scroll down to the checkout shipping fields
You should see something similar to:
This patch moves the printing of the "Shipping to Subscription Recipient" notice to a separate hook and introduces a cart contains gifted renewal helper function. With this change the …
> Fix Shipping to Recipient Notice Error

- includes/class-wcsg-admin.php
- includes/class-wcsg-cart.php
- includes/class-wcsg-checkout.php
- includes/class-wcsg-download-handler.php
- includes/class-wcsg-recipient-addresses.php
- includes/class-wcsg-recipient-details.php
- includes/class-wcsg-recipient-management.php
- includes/emails/class-wcsg-email-completed-renewal-order.php
- templates/emails/new-recipient-customer.php
- templates/emails/plain/new-recipient-customer.php
- templates/emails/plain/recipient-new-initial-order.php
- templates/emails/recipient-new-initial-order.php
- templates/html-add-recipient.php
- templates/related-orders.php
- woocommerce-subscriptions-gifting.php
Getting in some coding standard fixes to avoid 🔴 before I implement https://github.com/Prospress/prospress-coding-standards/issues/3
These changes shouldn't affect plugin behavior/functionality - but should still be reviewed carefully.
Some additional background info on the commits:
* 63e34f0 fixes some best practice indentation issues
* 38c7ef7 the `WordPress.WP.I18n` sniff is now part of the WordPress Core rule set. When there is more than 1 placeholder in a translatable string they should be numbered - for RTL languages etc. it means the order can be moved around.
* 1ddc37a fixes some best practice white space issues (`WordPress.Extra` ruleset)
* 54a5596 removes an extra `;`
* 23349a1 fixes a few yoda condition issues. There were a number of fixes in WPCS 0.9.0 for the …
> Coding standard fixes

- tests/bin/install.sh
- tests/bin/travis.sh
So that builds on PRs from people outside the Prospress organisation will run correct.
Similar to https://github.com/Prospress/woocommerce-subscriptions/commit/7a10098c150c6a1ab34dfc68438ced9596f8d3d1
> Stop using GitHub token for builds

- includes/class-wcsg-memberships-integration.php
WC Memberships allow store owners to grant memberships to variation parent ids so that purchasing any variation child of that product will grant membership. However, because WCSG Memberships integration made use of `wcs_get_canonical_product_id()`, only variation ids or standalone product ids could grant access. This PR fixes that.
To replicate on `master`: 
1. Setup a variable subscription product
2. Go to **WooCommerce->Memberships->Membership Plans->Add Membership Plan**
3. In the _"Grant access to people who purchase"_ field enter the variable product parent not the variation level products (https://cloudup.com/cwb4n30Lg1M).
4. Go the product's page, select a variation, enter a recipient email and add to cart.
5. Checkout
6. Go to **WooCommerce->Memberships** and notice no membership …
> Allow memberships to be granted on parent variable product ids

- templates/new-recipient-account.php
As @goldhat alluded to in https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/182#issuecomment-260143912 while testing the recipient details page I would use the storefront theme which will always display notices on all pages. This meant that while using other themes, error notices weren't displayed for invalid recipient details. 
For example:
`master`
- storefront: https://cldup.com/HfCIOELX9Z.png (notices displayed)
- theme: https://cloudup.com/cwDPHGNxN2x (no notices) 
`issue_182`
- storefront: https://cldup.com/HfCIOELX9Z.png (notices displayed with no duplication)
- theme: https://cldup.com/-Gj85a4S5x.png (notices displayed) 👍 
props @goldhat 
fixes #182 
replaces #184
> print notices on the recipient details page

- includes/class-wcsg-recipient-management.php
WC Subscriptions v2.1 added a new user has capability check when paying for renewal orders (https://github.com/Prospress/woocommerce-subscriptions/pull/1716). In order to maintain the feature which allows recipients to pay for renewal orders, Gifting must grant recipients that capability.
I also had to move `grant_recipient_capabilities()` back on its priority to ensure Subscriptions doesn't remove the capability ([here](https://github.com/Prospress/woocommerce-subscriptions/pull/1716/files#diff-7c66e9af84fe53fb819cc1a478205e1dR357)) after we've granted it.
To replicate:
- Purchase a subscription product for a test recipient
- Go to the edit subscription admin screen and trigger the "Create pending renewal order" action 
- Login as the recipient and view the newly created subscription …
> Allow recipients to pay renewal orders post WCS v2.1

- languages/woocommerce-subscriptions-gifting.pot
Users can easily translate a plugin with the plugin Loco Translate. But it's difficult for non-developers to get the internationalized strings for non-developers. I propose to provide the .pot file wit the plugin to ease the translation process.
> Add pot file

- includes/class-wcsg-admin.php
- includes/class-wcsg-cart.php
- includes/class-wcsg-checkout.php
- includes/class-wcsg-download-handler.php
- includes/class-wcsg-email.php
- includes/class-wcsg-memberships-integration.php
- includes/class-wcsg-recipient-addresses.php
- includes/class-wcsg-recipient-details.php
- includes/class-wcsg-recipient-management.php
- includes/emails/class-wcsg-email-completed-renewal-order.php
- includes/emails/class-wcsg-email-processing-renewal-order.php
- includes/emails/class-wcsg-email-recipient-new-initial-order.php
- includes/wcsg-compatibility-functions.php
- templates/new-recipient-account.php
- templates/related-orders.php
- tests/unit/wcsg-renewal-order-tests.php
- woocommerce-subscriptions-gifting.php
This PR introduces the changes needed to be compatible with WC 3.0. 
See https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/203#issuecomment-319263117 for the functionality I've tested. 
The changes are largely made up of replacing direct order/subscription property access with helper functions. 
Other changes are due to deprecated action hooks, and functions and general changes in the way WC core does things.
> WC 3.0 compatibility

- includes/class-wcsg-recipient-management.php
- languages/woocommerce-subscriptions-gifting.pot
If you purchase a gift product, "Recipient" label is displayed as its item meta label on 'Order received', 'My Account>Subscripitons>[Subscription]' pages and the related emails. This label is not translatable.
1. Fresh WP install + WooCommerce + WooCommerce Subscriptions + WooCommerce Subscriptions Gifting
2. Go to Settings>General and change your site language to something different than English
3. Make sure all strings are translated in woocommerce-subscriptions-gifting_LOCALE.po/mo files
4. Open a product page in the Frontend
5. Make it a gift, specifying a recipient
6. Place the order
7. Check if "Recipient" label is translated in "Order received" page
8. Check if "Recipient" label is translated in "My Account>Subscripitons>[Subscription]" page
9. Check if "Recipient" label is …
> Fix for issue_218 - Make 'Recipient' item meta label translatable

- includes/class-wcsg-cart.php
To replicate with the latest Subscriptions version (`2.2.11`+):
- Create a [pending renewal](https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/#section-13) order for a gifted subscription
- Place the renewal order in the cart by clicking "Pay" from the customer's My Account page or following the pay link on the edit order screen.
If you check out at this point the meta is doubled up (eg https://cloudup.com/cdg4ukf7l7q).
Because we already copy the recipient information into the cart when the customer resubscribes/manually renews it doesn't need to be copied through the cart in this way by Subscriptions core.
fixes #210
> Remove recipient line item meta from order again cart item meta

- includes/class-wcsg-checkout.php
- js/wcs-gifting.js
- templates/html-add-recipient.php
See #209 for issue description. 
To replicate: 
- place a couple of different subscription products with the same billing schedule into the cart
- navigate to the checkout page and enter a recipient and attempt to checkout. 
You should receive an error similar to:
```
PHP Notice:  Undefined index: 2017_09_01_monthly_username@example.com_0 in /wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-cart.php on line 1119
```
The issue is caused by a change in the recipient (which updates the recurring cart key) before the checkout is validated. Subscriptions expects to find a selected shipping method of each recurring cart and because the keys have changed, it doesn't exist. This issue is even more problematic when entering a recipient or changing a recipient leads to …
> Reload checkout after making a change to a recipient - fixes issues with incorrect shipping selection

- includes/class-wcsg-recipient-details.php
- templates/new-recipient-account.php
When an account is created for a recipient, on their first login they are displayed with a form to collect some extra information (like their shipping address) and change their password.
If you disable shipping from WC Settings (https://cloudup.com/cohPOMXyU7W) however, the shipping address fields are still displayed. On top of there being no reason to collect the recipient's shipping address in this scenario, this actually makes the form unsubmittable because the country is a required field but WC cannot populate the dropdown (https://cloudup.com/cVhtks_f9sU).
This PR fixes that and introduces a filter to allow third parties to filter the fields displayed. 
- 63ed508 - Moves the **Shipping Address** heading so that it appears above the Company field _before: …
> Only display shipping address fields on the new recipient form when shipping is enabled

- languages/woocommerce-subscriptions-gifting.pot
As described on issue #220, "View" button in My Account>Subscripitons>[Subscription] (related orders) is not translated.
If you purchase a gift product and check the subscription at 'My Account>Subscripitons>[Subscription]', "View" button in "Related orders" section is not translated (it is translated in non-gifted subscriptions).
1. Fresh WP install + WooCommerce + WooCommerce Subscriptions + WooCommerce Subscriptions Gifting
2. Go to Settings>General and change your site language to something different than English
3. Make sure all strings are translated in woocommerce-subscriptions-gifting_LOCALE.po/mo files
4. Open a product page in the Frontend
5. Make it a gift, specifying a recipient
6. Place the order
7. Check if "View" button is translated in "My …
> Fix for issue_220 - "View" button in My Account>Subscripitons>[Subscription] (related orders) is not translated

- includes/class-wcsg-admin.php
- includes/class-wcsg-cart.php
- includes/class-wcsg-checkout.php
- includes/class-wcsg-recipient-management.php
- includes/emails/class-wcsg-email-completed-renewal-order.php
- includes/emails/class-wcsg-email-processing-renewal-order.php
- woocommerce-subscriptions-gifting.php
This adds a recipient selection field to the edit subscription screen. 
This field allows admin to add, edit or remove the recipient from the subscription. The only restriction on this field is that the recipient and customer cannot be the same user.
Because subscription line items also store the recipient id, using this field will also update or delete subscription order item meta.
> Add recipient edit field to the edit subscription screen

- includes/class-wcsg-email.php
- includes/class-wcsg-recipient-management.php
WC 3.1 removed the dynamic email headings and subjects for emails which contained download links. 
In order for the correct headings to be sent to recipients and purchasers, Gifting would determine whether the email recipient had downloads and if they didn't, would use the `$email->heading` or `$email->subject` values to get the default heading/subject. These properties were removed (are now null) and using those properties [here](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/master/includes/class-wcsg-email.php#L245) caused blank email subjects to be returned.
This commit completely removes that process for sites running 3.1 + as it's no longer necessary.
**To replicate:**
WooCommerce: `3.1+`
WCS Gifting: `master`
1. Make sure dual download permissions are disabled …
> Don't reformat email subjects and headings post WC 3.1

- languages/woocommerce-subscriptions-gifting.pot
Some errors appear when opening the languages/woocommerce-subscriptions-gifting.pot file in poEdit (or in translation plugins like LocoTranslate)
1. Open poEdit
2. Click Archive>New Catalog from POT file and select languages/woocommerce-subscriptions-gifting.pot file
[Some errors appear]
I've checked the pot file and I see that "Recipient" string is defined more than once in languages/woocommerce-subscriptions-gifting.pot generating some errors when processing the language file. This seems to be the origin of the conflict. 
I see that the string is from different lines in our code but I understand that we want to use the same translation for both. If for some reason we need to differentiate them, we should consider adding some context to them.
> Fix for issue_230 - Errors in language (.pot) file

- includes/class-wcsg-email.php
This is resubmission of #239. 
- Fixes typo in the `WCSG_Email::send_new_recient_user_email()` function
- Deprecates the incorrect function
> Fix typo in function name - resubmission of PR 239

- includes/class-wcsg-query.php
Removes the call to the `WCS_Query::__construct()` which was duplicating all the callbacks attached in that class and leading to two sets of Subscription endpoints being added among other duplicate calls weren't breaking things but were unnecessary. 
I've replaced the call to `WCS_Query::__construct()` by calling `init_query_vars()` directly and attaching the hooks necessary to get the `new-recipient-account` endpoint working.
To replicate:
1. Checkout the latest WCS `master`
2. Navigate to the **WooCommce -> Settings -> Accounts**
3. Scroll down to the endpoints and you should see 2 copies of the Subscription endpoints. eg. https://cloudup.com/cp20GyxcCSp
This PR fixes that but to test that this hasn't broken the WCSG `new-recipient-account`:
1. Place a subscription in the cart.
2. Enter …
> Only attach callbacks & call functions necessary to the WCSG query class

- woocommerce-subscriptions-gifting.php
This as to prevent self-gifting, as described in #234.
> Check billing e-mail address doesn't match recipient's e-mail address

- woocommerce-subscriptions-gifting.php
Modified the script enqueueing to move the .js file to the footer to reduce the render blocking effect of too many scripts being loaded in the head. Needed to add the version number and 'in_footer' true to the enqueueing to shift it down.  Is there a reason we need this script to load in the <head>?  I'm testing on an existing installation and it appears to work fine being shifted to the footer.
> Updating script enqueueing to shift js to footer.

- tests/bootstrap.php
- woocommerce-subscriptions-gifting.php
This PR is inspired by #178 and #235, where some initialization issues were found to happen under certain circumstances. I tried to keep the changes to a minimum as to not break anything but at the same time address the following issues:
- Because our checks were occurring outside of any WP hook, we were implicitly relying on the default WP load order for plugins for things to work. And this does work most of the time, but it's not really reliable. For example, a minor change to the name of a plugin folder can break things. I moved initialization to `plugins_loaded`, where we can at least be certain that the classes we need have been included.
- If WooCommerce Subscriptions was disabled (but WooCommerce enabled), a call to `is_woocommerce_active()` (which is provided by WCS) resulted in a …
> Some changes to initialization and dependency checking

- includes/class-wcsg-recipient-management.php
- woocommerce-subscriptions-gifting.php
After #249 WCSG classes are now included and initialised after WC loaded (`woocommerce_loaded`). This means functions like `WCSG_Recipient_Management::attach_dependant_hooks()` wont ever run because by the time the class is included the hook its attached to, `woocommerce_loaded`, has already come and gone. 
To fix that now just attach the dependant hooks inside the init. 
To ensure the `wcsg_is_woocommerce_pre()` function is available, I also had to change when that function's containing file is included to the top of the list. 
Without this change, new recipient users aren't being created 😱
> Attach dependant hooks on init now that classes are inited after WC load

- woocommerce-subscriptions-gifting.php
Fixes the following error when setting recipient users on versions of WC prior to 3.0
```
PHP Notice:  Undefined variable: recipient_user_id in /wp-content/plugins/woocommerce-subscriptions-gifting/woocommerce-subscriptions-gifting.php on line 540
```
To replicate: 
1. on WC `2.6.14` attempt to purchase any subscription product for a recipient user
2. the error included above should occur immediately after submitting the checkout form
> Use user ID variable instead of undeclared variable

- includes/class-wcsg-download-handler.php
Similar to #257 this PR fixes errors when gifting filters the download permissions. 
To replicate on `master`: 
1. Turn on purchaser download permissions from **WooCommerce >
Settings > Subscriptions** (https://cloudup.com/cNK1m4ZTbc3)
1. Purchase any subscription product with downloadable files for a recipient
2. When the order-received page is loaded, you should get the following errors:
```
Undefined index: downloads_remaining in /wp-content/plugins/woocommerce/includes/class-wc-order.php on line 1378
PHP Notice:  Undefined index: access_expires in /wp-content/plugins/woocommerce/includes/class-wc-order.php on line 1379
```
The error is caused by Gifting filtering the download links so that we display the downloads belonging to the current user, however, we weren't including all the …
> Include downloads remaining & access expiration args in downloadable files filtered by Gifting

- includes/class-wcsg-query.php
In Subscriptions recently the `WCS_Query::endpoint_content()` function signature was updated to include a new argument, the subscription page number. This was added as part of https://github.com/Prospress/woocommerce-subscriptions/pull/2537.
`WCSG_Query` was overriding that function and so the following warnings were being thrown: 
```
PHP Warning:  Declaration of WCSG_Query::endpoint_content() should be compatible with WCS_Query::endpoint_content($current_page = 1) in /app/public/wp-content/plugins/woocommerce-subscriptions-gifting/includes/class-wcsg-query.php on line 75
```
This PR updates that function's signature to include that new arg but also deprecates that function and `WCSG_Query::add_menu_items()` because they are no longer necessary. 
As the new block comments suggest, I …
> Deprecate unused WCSG_Query functions and update their function signature

- includes/class-wcsg-email.php
- templates/emails/plain/recipient-completed-renewal-order.php
- templates/emails/plain/recipient-email-address-table.php
- templates/emails/plain/recipient-email-order-details.php
- templates/emails/plain/recipient-email-subscriptions-table.php
- templates/emails/plain/recipient-new-initial-order.php
- templates/emails/plain/recipient-processing-renewal-order.php
- templates/emails/recipient-completed-renewal-order.php
- templates/emails/recipient-email-address-table.php
- templates/emails/recipient-email-order-details.php
- templates/emails/recipient-email-subscriptions-table.php
- templates/emails/recipient-new-initial-order.php
- templates/emails/recipient-processing-renewal-order.php
After merging #250, there were a still few changes that needed to be made to simplify the recipient email templates. 
The changes include
- Refactoring the recipient's subscriptions details table (https://cloudup.com/c6luozKV7vr) to its own template to avoid duplicates of the same table being in multiple emails. 
- Refactoring the recipient's address section (https://cloudup.com/cX-0U1M9IP5) moving that table to its own template.
- Fixing the initial order email template which had some styling issues when purchasing multiple subscriptions with downloads (https://cloudup.com/cbWkCimPw-w)
- I also changed the initial order email template back to include the line items rather than just the subscription details table. 
- Other whitespace and style changes.
There's a known issue with download …
> Email template refactoring and tweaks

- includes/class-wcsg-template-loader.php
See #264 for the issue background. 
To replicate, make sure you're running WCS 2.2.19+ and then simply navigate to the **WooCommerce > Status** page. You should receive the following warning: 
```
PHP Notice:  Undefined index: order in /app/public/wp-content/plugins/woocommerce-subscriptions-gifting/includes/class-wcsg-template-loader.php on line 74
```
I've also rearranged the logic a little to be a bit more performance friendly. 
fixes #264
> Check arg exists when determining if template needs to be overridden
